// dsh-mnemosyne client module — registers a "Mnemosyne" section in the DSH
// Settings page (left nav, like dsh-market). Shows CLI status, memory stats,
// and Setup / Test buttons that call host HTTP routes (/mnemosyne/*).
//
// Format: window.__ModuleLoader__.load — the DSH client runtime evaluates this
// factory and receives a Cordis plugin (apply/name/inject). No bundler; we use
// React.createElement directly (no JSX) per the cordis-plugin-development guide.

window.__ModuleLoader__.load({ id: "dsh-mnemosyne", factory: (require) => {
  const module = { exports: {} };
  const exports = module.exports;
  Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

  const React = require("react");

  const NS = "dsh-mnemosyne";
  const LOCALE = {
    zh: {
      nav: "Mnemosyne 记忆",
      status: "状态",
      cliReady: "CLI 已就绪",
      cliMissing: "CLI 未安装",
      dataDir: "数据目录",
      memories: "记忆数量",
      setup: "安装 CLI",
      installing: "安装中…",
      setupDone: "安装完成",
      setupFail: "安装失败",
      test: "测试连接",
      testing: "测试中…",
      testOk: "连接正常",
      testFail: "连接失败",
      refresh: "刷新",
      configHint: "参数配置见下方表单（由 DSH 设置自动生成）",
      noStats: "尚未获取统计",
      error: "错误",
      loading: "加载中…",
    },
    en: {
      nav: "Mnemosyne",
      status: "Status",
      cliReady: "CLI ready",
      cliMissing: "CLI not installed",
      dataDir: "Data directory",
      memories: "Memories",
      setup: "Setup CLI",
      installing: "Installing…",
      setupDone: "Setup complete",
      setupFail: "Setup failed",
      test: "Test connection",
      testing: "Testing…",
      testOk: "Connection OK",
      testFail: "Connection failed",
      refresh: "Refresh",
      configHint: "Configuration fields are in the form below (auto-generated by DSH settings)",
      noStats: "No stats yet",
      error: "Error",
      loading: "Loading…",
    },
  };

  const name = "dsh-mnemosyne-client";
  // Only declare hard deps that the client runtime always provides.
  // webServer routes are reached via fetch (no client service needed).
  const inject = ["slots", "locale"];

  function MnemosynePanel({ t }) {
    const [diag, setDiag] = React.useState(null);
    const [busy, setBusy] = React.useState(null); // "setup" | "test" | "diag"
    const [msg, setMsg] = React.useState(null);

    const refresh = React.useCallback(async () => {
      setBusy("diag");
      setMsg(null);
      try {
        const r = await fetch("/mnemosyne/diagnose", { headers: { accept: "application/json" } });
        setDiag(await r.json());
      } catch (e) {
        setDiag({ ok: false, error: String(e?.message ?? e) });
      } finally {
        setBusy(null);
      }
    }, []);

    React.useEffect(() => { refresh(); }, [refresh]);

    const setup = async () => {
      setBusy("setup"); setMsg(null);
      try {
        const r = await fetch("/mnemosyne/setup", { method: "POST" });
        const data = await r.json();
        setMsg(data.ok ? t("setupDone") : t("setupFail") + ": " + (data.error || ""));
        if (data.ok) refresh();
      } catch (e) { setMsg(t("setupFail") + ": " + String(e?.message ?? e)); }
      finally { setBusy(null); }
    };

    const test = async () => {
      setBusy("test"); setMsg(null);
      try {
        const r = await fetch("/mnemosyne/test", { method: "POST" });
        const data = await r.json();
        setMsg(data.ok ? t("testOk") : t("testFail") + ": " + (data.error || ""));
      } catch (e) { setMsg(t("testFail") + ": " + String(e?.message ?? e)); }
      finally { setBusy(null); }
    };

    const total = (() => {
      const m = diag?.stats?.match(/Total memories:\s*(\d+)/);
      return m ? Number(m[1]) : null;
    })();

    return React.createElement("div", { style: { padding: "16px", display: "flex", flexDirection: "column", gap: "12px" } },
      // status card
      React.createElement("div", { style: { border: "1px solid var(--border)", borderRadius: "8px", padding: "12px" } },
        React.createElement("h3", { style: { margin: "0 0 8px" } }, t("status")),
        diag == null
          ? React.createElement("div", null, t("loading"))
          : React.createElement(React.Fragment, null,
              React.createElement("div", null,
                (diag.cliReady ? "✅ " : "⚠️ ") + (diag.cliReady ? t("cliReady") : t("cliMissing")),
                diag.path ? "  (" + diag.path + ")" : null),
              diag.dataDir ? React.createElement("div", null, t("dataDir") + ": " + diag.dataDir) : null,
              total != null ? React.createElement("div", null, t("memories") + ": " + total) : null,
              diag.ok === false && diag.error
                ? React.createElement("div", { style: { color: "var(--danger)" } }, t("error") + ": " + diag.error)
                : null,
            ),
      ),
      // actions
      React.createElement("div", { style: { display: "flex", gap: "8px", flexWrap: "wrap" } },
        React.createElement("button", { onClick: setup, disabled: !!busy },
          busy === "setup" ? t("installing") : t("setup")),
        React.createElement("button", { onClick: test, disabled: !!busy || !diag?.cliReady },
          busy === "test" ? t("testing") : t("test")),
        React.createElement("button", { onClick: refresh, disabled: !!busy }, t("refresh")),
      ),
      msg ? React.createElement("div", null, msg) : null,
      React.createElement("div", { style: { color: "var(--text-2)", fontSize: "13px" } }, t("configHint")),
    );
  }

  function apply(ctx) {
    ctx.effect(() => ctx.locale.register(NS, LOCALE), "dsh-mnemosyne: dictionaries");
    const t = ctx.locale.bind(NS);

    ctx.slots.inject("settings.section", () => {
      const off = ctx.slots.register(
        { name: "settings.section", id: "mnemosyne", order: 50, label: () => t("nav"), locale: NS, inject: () => ({ t }) },
        () => React.createElement(MnemosynePanel, { t })
      );
      return off;
    });
  }

  exports.apply = apply;
  exports.inject = inject;
  exports.name = name;
  return module.exports;
}});